/* ###
 * ROTH
 */
// ROTHSetup — ONE-CLICK setup for the public recipe. Run this once, right after importing
// analysis/le_image/flat_reloc.bin. It drives the whole pipeline so newcomers don't have to
// run seven scripts in a fragile order:
//
//   1. memory blocks   (ROTHCreateObjectMemory)   -- skipped if ROTH_OBJ1_CODE already exists
//   2. auto-analysis   (analyzeAll)               -- skipped if functions already present
//   3. canonical boundaries (ROTHDefineCanonicalBoundaries) -- deletes all fns, recreates the
//        exact canonical set incl. non-contiguous Watcom shared-code bodies. This REPLACES the
//        old FixMainSequence / FixTruncated / DefineCommandHandlers / DefineRendererSpan /
//        DefineSosVtable scripts (their carves are all in the stamped set), so boundaries are
//        deterministic regardless of which compiler spec you imported under.
//   4. DAS structs/types (ROTHApplyDasTypes)
//   5. engine names/comments/globals (ROTHApplyEngineNames)  -- LAST = authoritative names
//
// After this, switch the decompiler to Watcom for correct register args:
//   Set Language -> Watcom, then Analysis > One Shot > Decompiler Parameter ID.
// (Because boundaries are stamped, it no longer matters whether you imported under Borland or
//  Watcom -- the old "import Borland then switch" dance is gone.)
//
// PREREQ: ROTHDefineCanonicalBoundaries.java must be present (generated by
//   tools/gen_boundary_script.py from a ROTHExportBoundaries dump). If it's missing this
//   script says so and stops.
//@category ROTH
//@menupath Tools.ROTH.Setup (one-click)
import ghidra.app.script.GhidraScript;
import ghidra.program.model.mem.MemoryBlock;

public class ROTHSetup extends GhidraScript {

    public void run() throws Exception {
        if (currentProgram == null) {
            printerr("Open the imported ROTH program first.");
            return;
        }

        // 1. Memory blocks (only if not already built).
        MemoryBlock obj1 = currentProgram.getMemory().getBlock("ROTH_OBJ1_CODE");
        if (obj1 == null) {
            println("[ROTHSetup] 1/5 building LE object memory blocks...");
            runScript("ROTHCreateObjectMemory.java");
        } else {
            println("[ROTHSetup] 1/5 memory blocks already present - skipping.");
        }

        // 2. Auto-analysis (only if the program hasn't been analyzed yet). Its function carving
        //    is thrown away by step 3; we run it for the data/string/reference analysis.
        int nfns = currentProgram.getFunctionManager().getFunctionCount();
        if (nfns < 100) {
            println("[ROTHSetup] 2/5 running auto-analysis (this takes a minute)...");
            analyzeAll(currentProgram);
        } else {
            println("[ROTHSetup] 2/5 program already analyzed (" + nfns + " functions) - skipping.");
        }

        // 3. Stamp canonical boundaries (must exist).
        println("[ROTHSetup] 3/5 stamping canonical function boundaries...");
        try {
            runScript("ROTHDefineCanonicalBoundaries.java");
        } catch (IllegalArgumentException notFound) {
            printerr("[ROTHSetup] ROTHDefineCanonicalBoundaries.java is missing. Generate it with "
                + "tools/gen_boundary_script.py (from a ROTHExportBoundaries dump) and retry.");
            return;
        }

        // 4. DAS structures / types.
        println("[ROTHSetup] 4/5 applying DAS types...");
        runScript("ROTHApplyDasTypes.java");

        // 5. Engine names / comments / globals (authoritative, LAST).
        println("[ROTHSetup] 5/5 applying engine names...");
        runScript("ROTHApplyEngineNames.java");

        println("[ROTHSetup] DONE. Next: Set Language -> Watcom C/C++, then "
            + "Analysis > One Shot > Decompiler Parameter ID for correct register arguments.");
    }
}
